# Managed by debian-hypr. cream-blue-light.
[main]
font=JetBrainsMono Nerd Font:size=11
terminal=terminator -x
width=40
lines=12
prompt="> "

[colors]
background=fff8f0ff
text=2b4570ff
prompt=5b7fa5ff
input=1a2a3fff
match=a0403aff
selection=d5dfebff
selection-text=1a2a3fff
selection-match=a0403aff
border=4a90d9ff

[border]
width=2
radius=0
